-define(SYS_DEBUG(Format, Args), lager:debug("~p:~p "Format, [?MODULE,?LINE|Args])).
-define(SYS_INFO(Format, Args), lager:info("~p:~p "Format, [?MODULE,?LINE|Args])).
-define(SYS_WARN(Format, Args), lager:warning("~p:~p "Format, [?MODULE,?LINE|Args])).
-define(SYS_ERROR(Format, Args), lager:error("~p:~p "Format, [?MODULE,?LINE|Args])).
-define(SYS_FATAL(Format, Args), lager:critical("~p:~p "Format, [?MODULE,?LINE|Args])).
